name: Slither Audit

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  slither-audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install slither-analyzer

    - name: Run Slither
      run: |
        slither contracts/
